# Generated by Django 4.2.2 on 2023-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
