# Generated by Django 4.2.2 on 2023-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitapp', '0004_alter_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='experience',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='qualification',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='salary',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='apply_link',
            field=models.CharField(max_length=100),
        ),
    ]
